Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 25

Style/HashSyntax:
  Exclude:
    # for task :foo => :bar definitions
    - '**/Rakefile'
    - '**/*.rake'
    - '**/*.rake.rb'
